version: 2
updates:
  # Enable version updates for Python
  - package-ecosystem: "pip"
    directory: "/scraper"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "pip"
      include: "scope" 