name: Goose Tour Scraper

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Run at 8 AM UTC every day
    - cron: '0 8 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scraper/requirements.txt
        pip install pytest pytest-cov
        
    - name: Run tests
      run: |
        pytest scraper/test_scraper.py --cov=scraper --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true

  scrape:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scraper/requirements.txt
        
    - name: Run scraper
      run: python scraper/goose_scraper.py
      
    - name: Check for changes
      id: git-check
      run: |
        git add data/
        git diff --staged --quiet || echo "changes=true" >> $GITHUB_OUTPUT
        
    - name: Commit and push if changes
      if: steps.git-check.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "chore: Update tour dates [skip ci]"
        git push origin HEAD:master 